"use client";
import React, { useEffect, useRef, useState } from "react";
import Image from "next/image";

export default function GridCarousel() {
  const carouselRef = useRef(null);
  const [position, setPosition] = useState(0);

  useEffect(() => {
    const scrollSpeed = 0.5; // pixels per frame
    let animationId: number;

    const animate = () => {
      setPosition((prevPosition) => {
        // Reset position when we've scrolled enough
        if (prevPosition <= -1600) {
          return 0;
        }
        return prevPosition - scrollSpeed;
      });
      animationId = requestAnimationFrame(animate);
    };

    animationId = requestAnimationFrame(animate);

    return () => {
      cancelAnimationFrame(animationId);
    };
  }, []);

  // multiple grid segments for continuous flow
  interface GridSegmentProps {
    key: number;
    counterText: string;
    counterColor: string;
  }

  const renderGridSegment = ({ key }: GridSegmentProps) => (
    <div key={key} className="flex-shrink-0 grid grid-cols-12 gap-4 w-[800px]">
      {/* Left panel - Large image */}
      <div className="relative col-span-5 h-[480px]">
        <div className="w-full h-full relative">
          <Image
            src="/landscape.jpeg"
            alt="Landscape scene"
            layout="fill"
            objectFit="cover"
            priority={key === 1}
          />
        </div>
      </div>

      {/* Middle column */}
      <div className="col-span-4 grid grid-rows-2 gap-4">
        {/* Top image */}
        <div className="relative h-[240px] rounded-2xl ">
          <div className="w-full h-full relative">
            <Image
              src="/vintagecar.jpeg"
              alt="Vintage vehicle"
              layout="fill"
              objectFit="cover"
            />
          </div>
        </div>

        {/* Bottom counter panel */}
        <div className="relative bg-gray-900 h-[225px] flex flex-col rounded-2xl justify-center items-center">
          <div className="text-[#D2FF3A] text-5xl font-bold">48,000</div>
          <div className="text-white text-xs mt-2">IMAGES GENERATED BY</div>
          <div className="text-white text-xs">ARTIFICIAL INTELLIGENCE</div>
        </div>
      </div>

      {/* Right panel - Winter scene */}
      <div className="relative col-span-3 h-[480px]">
        <div className="w-full h-full relative">
          <Image
            src="/winter.jpeg"
            alt="Winter scene"
            layout="fill"
            objectFit="cover"
          />
        </div>
      </div>
    </div>
  );

  return (
    <div className="flex flex-col gap-4 w-full bg-black text-white overflow-hidden">
      {/* Header */}
      <div className="py-6 px-27">
        <h1 className="text-3xl font-bold">Journey Through Art of community</h1>
      </div>

      {/* Carousel container */}
      <div className="relative overflow-hidden">
        <div
          ref={carouselRef}
          className="flex gap-4 "
          style={{ transform: `translateX(${position}px)` }}>
          {renderGridSegment({
            key: 1,
            counterText: "12,400",
            counterColor: "text-purple-500",
          })}
          {renderGridSegment({
            key: 2,
            counterText: "27,800",
            counterColor: "text-green-500",
          })}
          {renderGridSegment({
            key: 3,
            counterText: "9,350",
            counterColor: "text-blue-500",
          })}
          {renderGridSegment({
            key: 4,
            counterText: "32,700",
            counterColor: "text-red-500",
          })}
        </div>
      </div>
    </div>
  );
}
