import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Turret_Road } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const turretRoad = Turret_Road({
  variable: "--font-turret_road",
  weight: ["700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ether Ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${turretRoad.variable} antialiased max-h-[3392px`}
        style={{
          backgroundImage: "url('/ethereclipse.png')",
          backgroundRepeat: "no-repeat",
          backgroundPositionY: "top",
        }}
        >
        {children}
        <Footer/>
      </body>
    </html>
  );
}
